ClassLibrary/WebHospital/Controllers/patientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassLibrary;

namespace WebHospital.Controllers
{
    public class patientsController : Controller
    {
        private Model1 db = new Model1();

        // GET: patients
        public ActionResult Index(patient patient)
        {
            List<patient> temp = new List<patient>();
            temp.Add(patient);
            return View(temp);
        }

        // GET: patients/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = db.patient.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // GET: patients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: patients/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性。有关
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "patientID,IDNumber,name,gender,age,contactInformation,birthday")] patient patient)
        {
            if (ModelState.IsValid)
            {
                db.patient.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: patients/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = db.patient.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: patients/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性。有关
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "patientID,IDNumber,name,gender,age,contactInformation,birthday")] patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: patients/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = db.patient.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            patient patient = db.patient.Find(id);
            db.patient.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClassLibrary/WebHospital/Controllers/registerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassLibrary;

namespace WebHospital.Controllers
{
    public class registerController : Controller
    {
        private Model1 db = new Model1();


        // GET: registrationSessions/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            registrationSession registrationSession = db.registrationSession.Find(id);
            if (registrationSession == null)
            {
                return HttpNotFound();
            }
            return View(registrationSession);
        }

        // GET: registrationSessions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: registrationSessions/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性。有关
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "registrationSessionID,registrationPersonnelID,patientID,registrationType,registrationObject,sessionTime,isStart,department")] registrationSession registrationSession)
        {
            if (ModelState.IsValid)
            {
                db.registrationSession.Add(registrationSession);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(registrationSession);
        }

        // GET: registrationSessions/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            registrationSession registrationSession = db.registrationSession.Find(id);
            if (registrationSession == null)
            {
                return HttpNotFound();
            }
            return View(registrationSession);
        }

        // POST: registrationSessions/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性。有关
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "registrationSessionID,registrationPersonnelID,patientID,registrationType,registrationObject,sessionTime,isStart,department")] registrationSession registrationSession)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registrationSession).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(registrationSession);
        }

        // GET: registrationSessions/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            registrationSession registrationSession = db.registrationSession.Find(id);
            if (registrationSession == null)
            {
                return HttpNotFound();
            }
            return View(registrationSession);
        }

        // POST: registrationSessions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            registrationSession registrationSession = db.registrationSession.Find(id);
            db.registrationSession.Remove(registrationSession);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: registrationSessions
        public ActionResult Index()
        {
            string idNumber = ((user)Session["Current"]).IDNumber;
            List<patient> pa = db.patient.Where(p => p.IDNumber == idNumber).ToList(); // to get the patientID of the current user
            long patientId = pa[0].patientID;
            List<registrationSession> his = db.registrationSession.Where(p => p.patientID == patientId).ToList(); // get all registrations from the user
            Session["RegistrationList"] = his;
            return View(his);
        }

        public ActionResult showOrder() // write a button that can activate this method
        {
            List<order> orders = new List<order>();
            if (Session["RegistrationList"] != null)
            {
                foreach (var regis in (List<registrationSession>)Session["RegistrationList"]) // get orders from registrations
                {
                    List<order> temp= db.order.Where(p => p.registrationSessionID == regis.registrationSessionID).ToList();
                    order Order = temp[0];
                    orders.Add(Order);
                }
                return View(orders);
            }
            else return View();
        }

        public ActionResult search()
        {
            return View(db.scheduling.ToList());
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult search(string department, DateTime time, string timeDetail) // return available appointment positions
        {
            List<medicalPersonnel> people = db.medicalPersonnel.Where(p => p.department == department).ToList();
            List<scheduling> availablePeople = new List<scheduling>();
            foreach (var person in people)
            {
                scheduling s = db.scheduling.Find(person.medicalPersonnelID);
                if (s.dutyTime == time && s.timeDetail == timeDetail) availablePeople.Add(s);
            }
            return View(availablePeople); // return a list of available # aligned with different departments
        }

        // leave a button on the right to display avialable positions for the doctor
        public int displayAvailableNumber(scheduling toSearch)
        {
            long personnelID = toSearch.medicalPersonnelID;
            int appointing = db.registrationSession.Where(p => p.time == toSearch.dutyTime && p.timeDetail == toSearch.timeDetail && p.medicalPersonnelId == personnelID).ToList().Count;
            int availableNumber = 30 - appointing;
            return availableNumber;
        }

        public ActionResult register(long? helperID, long patientID, long medicalPersonnelId, DateTime time, string department, string timeDetail)
        {
            if (Session["Current"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest); // not permitted to register without logging in
            }
            registrationSession s = new registrationSession()
            {
                isStart = true,
                registrationSessionID = (long)HttpContext.Application["registration"],
                patientID = patientID,
                medicalPersonnelId = medicalPersonnelId,
                time = time,
                timeDetail = timeDetail,
                sessionTime = DateTime.Now,
                department = department
            };

            HttpContext.Application["registration"] = (long)HttpContext.Application["registration"] + 1; // in case that the patient gets a second registration

            if (helperID != null) s.registrationPersonnelID = (long)helperID;
            db.registrationSession.Add(s);
            db.SaveChanges();

            order o = new order()
            {
                orderNumber = (long)HttpContext.Application["order"],
                registrationSessionID = s.registrationSessionID, 
                medicalPersonnelID = s.medicalPersonnelId,
                orderTime = DateTime.Now,
                orderType = "registration",
                orderStatus = "not paid", 
                payment = 5
            };

            HttpContext.Application["order"] = (long)HttpContext.Application["order"] + 1;
            db.order.Add(o);
            db.SaveChanges();
            // return View();
            return RedirectToAction("pay", o);
        }

        public ActionResult pay(order o) // difficult to implement without using API - not implemented yet
        {
            o.orderStatus = "paid";
            db.SaveChanges();

            return View(o);
        }

        public ActionResult edit()
        {
            return View();
        }

        public ActionResult delete()
        {
            return View();
        }



    }
}

ClassLibrary/WebHospital/Views/patients/Create.cshtml
@model ClassLibrary.patient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.patientID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.patientID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.patientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.gender)
                    @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contactInformation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contactInformation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contactInformation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClassLibrary/WebHospital/Views/patients/Delete.cshtml
@model ClassLibrary.patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contactInformation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contactInformation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.birthday)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
        </div>
    }
</div>

ClassLibrary/WebHospital/Views/patients/Details.cshtml
@model ClassLibrary.patient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contactInformation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contactInformation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.birthday)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.patientID }) |
</p>

ClassLibrary/WebHospital/Views/patients/Edit.cshtml
@model ClassLibrary.patient

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.patientID)

        <div class="form-group">
            @Html.LabelFor(model => model.IDNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.gender)
                    @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contactInformation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contactInformation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contactInformation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClassLibrary/WebHospital/Views/patients/Index.cshtml
@model IEnumerable<ClassLibrary.patient>
@using ClassLibrary

@{
    ViewBag.Title = "Index";
}

<h2>欢迎来到智慧医疗系统！</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contactInformation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.birthday)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contactInformation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.birthday)
        </td>
        <td>
            @Html.ActionLink("修改", "Edit", new { id=item.patientID }) |
            @Html.ActionLink("详细", "Details", new { id=item.patientID }) |
            @Html.ActionLink("删除", "Delete", new { id=item.patientID })
        </td>
    </tr>
}
    @Html.ActionLink("挂号", "search", "register")

</table>